include "amdsyntax";

[ShortDescription = "Bit Test and Complement"]
opcode x86 btc
{
	[FixedReg = 7] var `0F BA` (reg/mem16 value, imm8 bitindex);
	[FixedReg = 7] var `0F BA` (reg/mem32 value, imm8 bitindex);
	[FixedReg = 7] var `0F BA` (reg/mem64 value, imm8 bitindex);
	
	var `0F BB` (reg/mem16 value, reg16 bitindex);
	var `0F BB` (reg/mem32 value, reg32 bitindex);
	var `0F BB` (reg/mem64 value, reg64 bitindex);
}
