include "amdsyntax";

[ShortDescription = "Bit Test and Set"]
opcode x86 bts
{
	[FixedReg = 5] var `0F BA` (reg/mem16 value, imm8 bitindex);
	[FixedReg = 5] var `0F BA` (reg/mem32 value, imm8 bitindex);
	[FixedReg = 5] var `0F BA` (reg/mem64 value, imm8 bitindex);
	
	var `0F AB` (reg/mem16 value, reg16 bitindex);
	var `0F AB` (reg/mem32 value, reg32 bitindex);
	var `0F AB` (reg/mem64 value, reg64 bitindex);
}
