include "amdsyntax";

alias dest = destination;

[ShortDescription = "Decrement by 1"]
[CanLock = true]
opcode x86 dec
{
	[SupportedModes = ProtectedReal] var `48` ([Encoding = OpcodeAdd] reg16 dest);
	[SupportedModes = ProtectedReal] var `48` ([Encoding = OpcodeAdd] reg32 dest);
	
	[FixedReg = 1] var `FE` (reg/mem8  dest);
	[FixedReg = 1] var `FF` (reg/mem16 dest);
	[FixedReg = 1] var `FF` (reg/mem32 dest);
	[FixedReg = 1] var `FF` (reg/mem64 dest);
}
