include "amdsyntax";

alias dest = destination;

[ShortDescription = "Increment by 1"]
[CanLock = true]
opcode x86 inc
{
	[ValidIn64BitMode = false] var `40` ([Encoding = OpcodeAdd] reg16 dest);
	[ValidIn64BitMode = false] var `40` ([Encoding = OpcodeAdd] reg32 dest);
	
	[FixedReg = 0] var `FE` (reg/mem8  dest);
	[FixedReg = 0] var `FF` (reg/mem16 dest);
	[FixedReg = 0] var `FF` (reg/mem32 dest);
	[FixedReg = 0] var `FF` (reg/mem64 dest);
}
